# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1500)),
                ('img_title', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=1500)),
                ('item_price', models.CharField(max_length=1500)),
                ('item_amount', models.CharField(max_length=1500)),
                ('item_total', models.CharField(max_length=1500)),
                ('item_date', models.DateField(auto_now=True)),
                ('item_description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='M2awel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('job', models.CharField(max_length=1500)),
                ('money', models.IntegerField()),
                ('paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_paid', models.IntegerField()),
                ('action_date', models.DateField(auto_now=True)),
                ('m2awel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.M2awel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1500)),
                ('user_age', models.IntegerField()),
                ('user_email', models.CharField(max_length=1500)),
                ('user_password', models.CharField(max_length=1500)),
                ('user_role', models.CharField(choices=[('Accountant', 'Accountant'), ('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='m2awel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
    ]
