# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
    ]
