# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160219_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='shek',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
